<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ciclos</title>
    <style>
        body{
            background-color: #E85F79;
            text-align: center;
        }
    </style>
</head>
<body>

   
        <?php
        
            while (rand(1,10)!= 5) {
        ?> <!-- rand asigna valores aleatorios puede asignar cualquier valor-->
        <img src="php-logo.png" alt="">
        <?php
            }
        ?>

</body>
</html>